/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as IndexImport } from './app/routes/index'
import { Route as AuthSignUpRouteImport } from './app/routes/auth/sign-up/route'
import { Route as AuthSignInRouteImport } from './app/routes/auth/sign-in/route'
import { Route as AuthRecoveryPasswordRouteImport } from './app/routes/auth/recovery-password/route'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRouteRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRouteRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthRecoveryPasswordRouteRoute = AuthRecoveryPasswordRouteImport.update({
  id: '/auth/recovery-password',
  path: '/auth/recovery-password',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/recovery-password': {
      id: '/auth/recovery-password'
      path: '/auth/recovery-password'
      fullPath: '/auth/recovery-password'
      preLoaderRoute: typeof AuthRecoveryPasswordRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/recovery-password': typeof AuthRecoveryPasswordRouteRoute
  '/auth/sign-in': typeof AuthSignInRouteRoute
  '/auth/sign-up': typeof AuthSignUpRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/recovery-password' | '/auth/sign-in' | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/recovery-password' | '/auth/sign-in' | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/auth/recovery-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRecoveryPasswordRouteRoute: typeof AuthRecoveryPasswordRouteRoute
  AuthSignInRouteRoute: typeof AuthSignInRouteRoute
  AuthSignUpRouteRoute: typeof AuthSignUpRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRecoveryPasswordRouteRoute: AuthRecoveryPasswordRouteRoute,
  AuthSignInRouteRoute: AuthSignInRouteRoute,
  AuthSignUpRouteRoute: AuthSignUpRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/recovery-password",
        "/auth/sign-in",
        "/auth/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/recovery-password": {
      "filePath": "auth/recovery-password/route.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in/route.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
